import AppKit

public enum PasteboardCodec {
    public enum CaptureError: LocalizedError {
        case tooLarge, changedDuringRead
        public var errorDescription: String? {
            switch self {
            case .tooLarge: return "This clipboard item exceeds the 32 MB capture limit."
            case .changedDuringRead: return "The clipboard changed while it was being read."
            }
        }
    }
    public static func read(from board: NSPasteboard, ignoreConfidential: Bool = true, ignoreTransient: Bool = true) throws -> ClipboardPayload? {
        let changeCount = board.changeCount
        let types = Set((board.types ?? []).map(\.rawValue))
        if ignoreConfidential && types.contains("org.nspasteboard.ConcealedType") { return nil }
        if ignoreTransient && !types.isDisjoint(with: ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]) { return nil }
        var size = 0
        let items = try (board.pasteboardItems ?? []).map { item -> [String: Data] in
            var result: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    size += data.count
                    guard size <= 32 * 1024 * 1024 else { throw CaptureError.tooLarge }
                    result[type.rawValue] = data
                }
            }
            return result
        }
        guard board.changeCount == changeCount else { throw CaptureError.changedDuringRead }
        let payload = ClipboardPayload(items: items)
        guard !items.isEmpty, !payload.isBlank else { return nil }
        return payload
    }
    @discardableResult public static func write(_ payload: ClipboardPayload, to board: NSPasteboard, plainText: Bool = false) -> Bool {
        if plainText {
            guard !payload.text.isEmpty else { return false }
            board.clearContents()
            return board.setString(payload.text, forType: .string)
        }
        let items = payload.items.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: .init(type)) }
            return item
        }
        guard !items.isEmpty else { return false }
        board.clearContents()
        return board.writeObjects(items)
    }
}
